version: '3.4'

services:
  postgres:
    image: postgres
    container_name: container-postgresql
    environment:
      POSTGRES_DB: reactive_codechella_db
      POSTGRES_USER: laurocorreia
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  codechella-webflux:
    image: laurocorreia/spring-reactive-codechella:1.0.0
    env_file:
      - .env
    depends_on:
      - postgres  
    ports:
      - 8080:8080    
    volumes:
      - .:/app

