spring:
  application:
    name: codechella

  webflux:
    problemdetails:
      enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_codechella_db
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  flyway:
    url: jdbc:postgresql://localhost:5432/reactive_codechella_db
    password: ${PASSWORD_DB}
    user: ${USERNAME_DB}

deepL-api-key: ${API_KEY}
