CREATE TABLE EVENTS
(
    ID          BIGSERIAL    NOT NULL,
    TYPE        VARCHAR(30)  NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    DATE        DATE,
    DESCRIPTION VARCHAR(200) NOT NULL,

    PRIMARY KEY (ID)
);